name: "dieton"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: "always"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: "unless-stopped"

volumes:
  db_data: